# Generated by Django 4.2.7 on 2023-12-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_published'),
        ('main', '0002_category_comment_article_category'),
    ]

    operations = [
    ]
